### ISSUE TITLE
Frage zur Config

### ISSUE THREAD

**Issue by mr-gosh** [svenwal/gaszaehler-home-assistant-esphome#1]
Hey, vielen Dank für das gut aufbereitete repo - bin durch deinen Kommentar hierher gelangt und es hat damit super geklappt.

Es gibt zwei offene Fragen:
Du schreibst dass man von HA aus den Wert anchbessern kann (nach eienr zwischenablesung z.B. aber wie geht das?

Und ich habe einen Zähler der genau so zu funktionieren scheint wie deiner - nur dass beiu mir in den Status nachrichten irgendwie zu viele Nachkommastellen sind - ist da irgendwo ne "x0.01" zu viel?

in der Statusnachricht vom esp webserver steht zb:

13:23:52 | [D] | [sensor:093] | 'Gasverbrauch': Sending state 14647.71973 m³ with 2 decimals of accuracy
-- | -- | -- | --

Aber mein Zählerwert in der Config lautet 1464761 und der konkrete Zählerstand auf dem Zähler lautet 14647,61

Habe ich nen Denkfehler?

Hier meine aktuelle Config:

```yaml
esphome:
  name: esp01-2
  friendly_name: ESP01-2

esp8266:
  board: esp01_1m
  # Total Counter im Flash speichern
  restore_from_flash: true

preferences:
  flash_write_interval: 5min

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: $"secret"
  services:
    - service: update_counter_pulses
      variables:
        counter_pulses: int
      then:
        - globals.set:
            id: pulses_sum
            value: !lambda 'return counter_pulses;'

ota:
  password: $"secret"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp01-2 Fallback Hotspot"
    password: $"secret"

web_server:
  port: 80
  auth:
    username: admin
    password: $"secret"

captive_portal:

# Gaszähler https://github.com/svenwal/gaszaehler-home-assistant-esphome

globals:
  - id: pulses_sum
    type: int
    restore_value: yes
    initial_value: '1464761'  # hier Gaszählerstand initialisieren, ohne Komma, mit Nachkommastellen
binary_sensor:
  - platform: gpio
    id: internal_pulse_counter
    pin:
      number: GPIO2
      mode: INPUT_PULLUP
    name: "Live-Impuls"
    filters:
      - delayed_on: 10ms
    on_press:
      then:
#        - lambda: id(pulses_sum) += 1;
#        - output.turn_off: led  # optional: für eine LED, die den Gaszählerpuls visualisiert
    on_release:
      then:
        - lambda: id(pulses_sum) += 1;
#        - output.turn_on: led  # optional: für eine LED, die den Gaszählerpuls visualisiert
sensor:
  - platform: template
    name: "Gasverbrauch"
    device_class: gas
    unit_of_measurement: "m³"
    state_class: "total_increasing"
    icon: "mdi:fire"
    accuracy_decimals: 2
    lambda: |-
      return id(pulses_sum) * 0.01;
# Optional: Diese LED soll blinken, sobald ein Signal vom Gaszähler erkannt wird
#output:
#  - platform: gpio
#    pin: GPIO0
#    id: 'led'
```
